name: Release Packages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
#  verify:
#    name: Verify release
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v6
#        with:
#          fetch-depth: 0
#
#      - name: Setup pnpm
#        uses: pnpm/action-setup@v6
#        with:
#          run_install: false
#
#      - name: Setup Node.js environment
#        uses: actions/setup-node@v6
#        with:
#          node-version: 24
#          cache: pnpm
#
#      - name: Install dependencies
#        run: pnpm install --frozen-lockfile
#
#      - name: Install Playwright Browsers
#        run: pnpm dlx playwright install chromium
#
#      - name: Run CI
#        run: pnpm run ci

  release:
    name: Release
#    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
          publish: pnpm release
          commit: "chore: release packages"
          title: "chore: release packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
